
local constants = require("libs/Constants")

-- data.raw.fluid["alien-goo"].emissions_multiplier = 3
-- data.raw.fluid["alien-goo"].fuel_value = "2.5MJ"

-- data.raw["assembling-machine"]["centrifuge"].fluid_boxes =
--     {
-- 	{
-- 	    production_type = "input",
-- 	    pipe_covers = pipecoverspictures(),
-- 	    base_area = 10,
-- 	    base_level = -1,
-- 	    pipe_connections = {{ type="input", position = {-1, -2} }}
-- 	},
-- 	{
-- 	    production_type = "input",
-- 	    pipe_covers = pipecoverspictures(),
-- 	    base_area = 10,
-- 	    base_level = -1,
-- 	    pipe_connections = {{ type="input", position = {1, -2} }}
-- 	},
-- 	{
-- 	    production_type = "output",
-- 	    pipe_covers = pipecoverspictures(),
-- 	    base_level = 2,
-- 	    pipe_connections = {{ position = {-1, 2} }}
-- 	},
-- 	{
-- 	    production_type = "output",
-- 	    pipe_covers = pipecoverspictures(),
-- 	    base_level = 2,
-- 	    pipe_connections = {{ position = {1, 2} }}
-- 	}
--     }


-- data.raw["ammo"]["firearm-magazine"].ammo_type = {
--     category = "bullet",
--     target_type = "position",
--     clamp_position = true,
--     action =
-- 	{
-- 	    type = "direct",
-- 	    force = "enemy",
-- 	    action_delivery =
-- 		{
-- 		    type = "projectile",
-- 		    projectile = "cannon-projectile2",
-- 		    starting_speed = 1,
-- 		    direction_deviation = 0.1,
-- 		    range_deviation = 0.5,
-- 		    max_range = 15,
-- 		    min_range = 5,
-- 		    source_effects =
-- 			{
-- 			    type = "create-explosion",
-- 			    entity_name = "explosion-gunshot"
-- 			},
-- 		}
-- 	},
-- }
